'use strict';
const assert = require('node:assert/strict');
const { compareTexts: compare } = require('./compare.js');
let result = compare('one two three', 'one four three');
assert.equal(result.matches, 2);
assert.equal(result.distance, 1);
assert.ok(Math.abs(result.similarity - 200 / 3) < 1e-10);
assert.deepEqual([...result.matchedA].sort(), [0, 4]);
result = compare('one two', 'one two three');
assert.equal(result.accuracyA, 50);
assert.ok(Math.abs(result.accuracyB - 200 / 3) < 1e-10);
assert.equal(result.similarity, 80);
assert.equal(compare('', '').similarity, 100);
assert.equal(compare('', '').accuracyA, 100);
assert.equal(compare('', 'word').accuracyA, 0);
assert.equal(compare('word', '').accuracyA, 0);
assert.equal(compare('Hello, WORLD!', 'hello world', { ignoreCase: true, ignorePunctuation: true }).similarity, 100);
assert.equal(compare('Hello', 'hello').matches, 0);
assert.equal(compare('hello!', 'hello').matches, 0);
assert.equal(compare('a b a', 'a a').matches, 2);
assert.equal(compare('a b', 'b a').matches, 1);
result = compare('“Hi!” ...', 'hi', { ignoreCase: true, ignorePunctuation: true });
assert.equal(result.similarity, 100);
assert.equal(result.A.wordCount, 2);
assert.equal(result.A.words.length, 1);
assert.equal(compare('...', '!', { ignorePunctuation: true }).similarity, 100);
assert.equal(compare('a\n\t b', 'a b').similarity, 100);
assert.equal(compare('$', '+', { ignorePunctuation: true }).matches, 0);
assert.equal(compare('<script>alert(1)</script>', '').A.parts[0], '<script>alert(1)</script>');
const start = performance.now();
result = compare('a '.repeat(5000), 'b '.repeat(5000));
assert.equal(result.distance, 5000);
assert.equal(result.similarity, 0);
console.log(`Comparison checks passed, including maximum-size inputs (${Math.round(performance.now() - start)} ms).`);
